# Generated by Django 4.0.3 on 2022-04-08 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_to',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
